# Generated by Django 5.0.1 on 2024-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_student_other_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='other_school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
